### ISSUE TITLE
אתרי לימודים

### ISSUE THREAD

**Issue by shayaulman** [shayaulman/kosher-code#25]
### English
- https://www.udemy.com/
- https://www.coursera.org/
 some free
- https://www.codecademy.com/
 some free 
- https://www.khanacademy.org/
 free

### Hebrew
- https://www.tocode.co.il/
- https://webmaster.org.il/
- https://she-codes.org/he/home-heb/
- https://cyber.org.il/online_courses/
 free

# Todo:

- [x] Build the page
- [x] Some easy way to show the logo's?

**Comment by yossizahn** [comment]
> Some easy way to show the logo's?

Favicons can be retrieved from `https://www.google.com/s2/favicons?domain={domain name}`

**Comment by shayaulman** [comment]
I just saw it yesterday in [this](https://github.com/JonathanDn/vue-companies-israel/pull/13/commits/742ca3085abb8d171c79c2d7b530119b8f7d18f4) commit...
(I never knew about it before)
The question is if it'll look good enough on more a bigger ratio. I'll check it out.
Thanks!

**Comment by shayaulman** [comment]
https://github.com/shayaulman/kosher-code/commit/8a8321bfedc8484734928fd89c1958d46dbf500c

**Comment by shayaulman** [comment]
- [ ] https://flexboxfroggy.com/
- [ ] https://cssgridgarden.com/
- [ ] https://laracasts.com/
- [ ] https://wesbos.com/
- [ ] https://www.leveluptutorials.com/

**Comment by zvizvi** [comment]
כדאי להפריד בין אתרי לימודים - לאתרי עזר לתרגול ושיפור המיומנות בשפה

**Comment by shayaulman** [comment]
אולי יהיה צורך כשהרשימה תגדל
לבינתיים, אני חושב, מספיק לייעל את התגיות

**Comment by ynigun** [comment]
יש הרבה בלוגים קטנים או בתחומים מאוד מסויים
 שלא שייכים כל כך לרשימה של הבלוגים
אולי אפשר לדחוף אותם באתרי\חומרי לימוד?

**Comment by ynigun** [comment]
הנה עוד אתר שעכשיו נפתח בנטפרי
https://www.itpro.tv
נראה שיש שם חומר מעניין
